FROM openjdk:11-jre-slim

WORKDIR /app

# JAR 파일 복사
COPY build/libs/MGcinema-0.0.1-SNAPSHOT.jar app.jar

# 포트 노출 (오라클 클라우드는 8080 포트 사용)
EXPOSE 8080

# 환경변수 설정
ENV SPRING_PROFILES_ACTIVE=prod

# 애플리케이션 실행
ENTRYPOINT ["java", "-jar", "app.jar"]
